name: Release Upload

# description:	Auto upload apk files onto release page, 
# 				but you must add a new release first (without any apk files).

# author:		kylecorry31
# repo:			https://github.com/kylecorry31/Trail-Sense

on:
  release:
    types: [published]

env:
    # Signing INFO
    DEV_STORE_FILE: ../debug.keystore
    # Don't forget to put the key file into project root !
    DEV_STORE_PASSWORD: android
    DEV_KEY_ALIAS: androiddebugkey
    DEV_KEY_PASSWORD: android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17k

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: |
          ./gradlew assembleDev \
            -Ddev_store_file=${{ env.DEV_STORE_FILE }} \
            -Ddev_store_password="${{ env.DEV_STORE_PASSWORD }}" \
            -Ddev_key_alias="${{ env.DEV_KEY_ALIAS }}" \
            -Ddev_key_password="${{ env.DEV_KEY_PASSWORD }}"

      - name: Upload to release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: Trail-Sense-${{ github.event.release.tag_name }}-dev.apk
          path: ./app/build/outputs/apk/dev/app-dev.apk
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build GitHub Release APK
        run: |
          ./gradlew assembleGithub \
            -Ddev_store_file=${{ env.DEV_STORE_FILE }} \
            -Ddev_store_password="${{ env.DEV_STORE_PASSWORD }}" \
            -Ddev_key_alias="${{ env.DEV_KEY_ALIAS }}" \
            -Ddev_key_password="${{ env.DEV_KEY_PASSWORD }}"

      - name: Upload GitHub release APK to release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: Trail-Sense-${{ github.event.release.tag_name }}-github-release.apk
          path: ./app/build/outputs/apk/github/app-github.apk
          repo-token: ${{ secrets.GITHUB_TOKEN }}